In [2]:
# Task 1: Creating Arrays
# 1. Write a Python program to:
# o Create a 1D NumPy array of 10 integers ranging from 1 to 10.
# o Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.
# o Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
# 2. Display the shape, size, and datatype of each array.

import numpy as np
array_1d = np.arange(1, 11)
array_2d = np.arange(1, 10).reshape(3, 3)
array_3d = np.random.rand(3, 5, 3)

# Display
def display_info(name, array):
    print(f"{name}:\n{array}")
    print(f"Shape: {array.shape}")
    print(f"Size: {array.size}")
    print(f"Data Type: {array.dtype}")
    print()

# Display
display_info("1D Array", array_1d)
display_info("2D Array", array_2d)
display_info("3D Array", array_3d)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Data Type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data Type: int64

3D Array:
[[[0.10271949 0.60404169 0.00507908]
  [0.03736974 0.00422527 0.69221951]
  [0.47654241 0.58159863 0.92507359]
  [0.53615752 0.89037666 0.13666498]
  [0.24195139 0.38542127 0.84492592]]

 [[0.67606274 0.06012056 0.05238238]
  [0.81777213 0.87214186 0.4033052 ]
  [0.67321976 0.36971135 0.06926677]
  [0.07394846 0.08726302 0.45054485]
  [0.83273108 0.05766157 0.73607438]]

 [[0.40355973 0.78017386 0.57744721]
  [0.93097422 0.90779165 0.5900225 ]
  [0.96346893 0.19327145 0.58129382]
  [0.89325954 0.89694887 0.10544226]
  [0.01008108 0.81923843 0.97601477]]]
Shape: (3, 5, 3)
Size: 45
Data Type: float64



In [3]:
# Task 2: Array Indexing and Slicing
# 1. Create a NumPy array from the following list:
# data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# 2. Write a Python program to:
# o Retrieve the first three elements of the array.
# o Retrieve every alternate element of the array.
# o Reverse the array.
# 3. Perform the above operations and display the results

data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
array = np.array(data)
first_three = array[:3]
alternate_elements = array[::2]
reversed_array = array[::-1]

# Display 
print("Original Array:", array)
print("First Three Elements:", first_three)
print("Every Alternate Element:", alternate_elements)
print("Reversed Array:", reversed_array)


Original Array: [10 20 30 40 50 60 70 80 90]
First Three Elements: [10 20 30]
Every Alternate Element: [10 30 50 70 90]
Reversed Array: [90 80 70 60 50 40 30 20 10]


In [4]:
# Task 3: Mathematical Operations
# 1. Create two NumPy arrays, A and B, each with 5 random integers between 1 and 20.
# 2. Write a Python program to:
# o Add, subtract, multiply, and divide the two arrays element-wise.
# o Compute the dot product of the arrays.
# o Find the mean, median, standard deviation, and variance of array A.
# o Identify the maximum and minimum values in array B and their indices.

a = np.random.randint(1, 21, 5)
b = np.random.randint(1, 21, 5)

add = a + b
subtract = a - b
multiply = a * b
divide = a / b 

dot_product = np.dot(a, b)

mean_A = np.mean(a)
median_A = np.median(a)
std_A = np.std(a)
var_A = np.var(a)

max_B = np.max(b)
min_B = np.min(b)
max_index = np.argmax(b)
min_index = np.argmin(b)

# Display 
print("Array a:", a)
print("Array b:", b)

print("\nAddition:", add)
print("Subtraction:", subtract)
print("Multiplication:", multiply)
print("Division:", divide)

print("\nDot Product:", dot_product)

print("\nIn array a:")
print("Mean:", mean_A)
print("Median:", median_A)
print("Standard Deviation:", std_A)
print("Variance:", var_A)

print("\nIn array b:")
print("Maximum Value:", max_B, "at Index:", max_index)
print("Minimum Value:", min_B, "at Index:", min_index)


Array a: [10 16 17 17  9]
Array b: [11 20 15  5  6]

Addition: [21 36 32 22 15]
Subtraction: [-1 -4  2 12  3]
Multiplication: [110 320 255  85  54]
Division: [0.90909091 0.8        1.13333333 3.4        1.5       ]

Dot Product: 824

In array a:
Mean: 13.8
Median: 16.0
Standard Deviation: 3.54400902933387
Variance: 12.559999999999999

In array b:
Maximum Value: 20 at Index: 1
Minimum Value: 5 at Index: 3


In [5]:

# Task 4: Reshaping and Transposing
# 1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
# 2. Write a Python program to:
# o Reshape the array into a 2D array of shape (4, 3).
# o Reshape the array into a 3D array of shape (2, 2, 3).
# o Transpose the reshaped 2D array and display its shape.

array_1d = np.arange(1, 13)
array_2d = array_1d.reshape(4, 3)
array_3d = array_1d.reshape(2, 2, 3)
transposed_2d = array_2d.T 

# Display 
print("1D Array:", array_1d)
print("\nReshaped 2D Array (4,3):\n", array_2d)
print("\nReshaped 3D Array (2,2,3):\n", array_3d)
print("\nTransposed 2D Array:\n", transposed_2d)
print("\nShape of Transposed Array:", transposed_2d.shape)


1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 2D Array (4,3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped 3D Array (2,2,3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transposed 2D Array:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

Shape of Transposed Array: (3, 4)


In [6]:
# Task 5: Boolean Masking and Filtering
# 1. Create a NumPy array with 15 random integers between 10 and 50.
# 2. Write a Python program to:
# o Find all elements greater than 25.
# o Replace all elements less than 30 with 0.
# o Count the number of elements divisible by 5.

array = np.random.randint(10,51,15)
greater = array[array > 25]
modified_array = np.where(array < 30,0,array)
count = np.sum(array%5==0)

# Display 
print("Array:", array)
print("\nElements greater than 25:", greater)
print("\nModified Array (values < 30 set to 0):", modified_array)
print("\nCount of elements divisible by 5:", count)

Array: [23 26 44 21 32 33 39 47 23 18 38 41 36 40 10]

Elements greater than 25: [26 44 32 33 39 47 38 41 36 40]

Modified Array (values < 30 set to 0): [ 0  0 44  0 32 33 39 47  0  0 38 41 36 40  0]

Count of elements divisible by 5: 2


In [7]:
# Task 6: Working with Built-in Functions
# 1. Use NumPy's built-in functions to:
# o Create an array of 10 equally spaced values between 0 and 1.
# o Create an identity matrix of size 4x4.
# o Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

array = np.linspace(0, 1, 10) 
matrix = np.eye(4)
array_2 = np.random.randint(1,101,20)
sort_array = np.sort(array_2)
largest_element = sort_array[-5:]

# Display
print("An Array of 10 equally spaced values between 0 and 1:\n", array)
print("\n4x4 Identity Matrix:\n", matrix)
print("\nRandom Array of 20 integers between 1 and 100:", array_2)
print("\nSorted Array:", sort_array)
print("\nthe 5 largest elements in the array:", largest_element)

An Array of 10 equally spaced values between 0 and 1:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random Array of 20 integers between 1 and 100: [29 61 33 26 97 39 29 68 69  4 38 71 98 10 77 49 87 41 19 70]

Sorted Array: [ 4 10 19 26 29 29 33 38 39 41 49 61 68 69 70 71 77 87 97 98]

the 5 largest elements in the array: [71 77 87 97 98]


In [8]:
# Task 7: Generic
# 1. Create a Python program that:
# o Generates two large random arrays of size (100, 100).
# o Performs matrix multiplication on the two arrays.
# o Finds the determinant and inverse of the resulting matrix (if possible).
# o Measures the time taken to complete these operations.

import time
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)
start_time = time.time()
matrix_mul = np.matmul(A, B)
det = np.linalg.det(matrix_mul)
if det != 0:
    inverse = np.linalg.inv(matrix_mul)
    inverse_status = ("Inverse computed successfully.")
else:
    inverse_status = ("Inverse does not exist.")

end_time = time.time()
total_time = end_time - start_time

# Display 
print("Matrix multiplication, determinant, and inverse operation completed.")
print(f"Determinant: {det:.4e}")
print(inverse_status)
print(f"Total time taken: {total_time:.4f} seconds")



Matrix multiplication, determinant, and inverse operation completed.
Determinant: -7.7407e+51
Inverse computed successfully.
Total time taken: 0.1023 seconds
